#!/usr/bin/env python3
"""Generate China geo-split route data from APNIC delegation records.

Outputs (all committed, refresh with: bash scripts/update-chnroute.sh):
  configs/chnroute_v4.txt                       CN IPv4 CIDRs (aggregated)
  cmd/chimerac/chnroute_v4.txt                  embedded copy for the CLI
  apps/windows/internal/bridge/chnroute_v4.txt  embedded copy for the GUI
  apps/android/app/src/main/res/values/split_routes_geo.xml
          complement of (CN ∪ private/reserved): the whitelist of public
          space that should traverse the VPN in geo-split mode
"""
import ipaddress
import sys
import urllib.request

APNIC_URL = "https://ftp.apnic.net/stats/apnic/delegated-apnic-extended-latest"

# RFC1918 + loopback + link-local + CGN + multicast/reserved: never routed
# into the tunnel on any platform.
PRIVATE = [
    "0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8",
    "169.254.0.0/16", "172.16.0.0/12", "192.0.0.0/24", "192.0.2.0/24",
    "192.168.0.0/16", "198.18.0.0/15", "198.51.100.0/24", "203.0.113.0/24",
    "224.0.0.0/4", "240.0.0.0/4",
]


def fetch_cn_intervals():
    sys.stderr.write(f"fetching {APNIC_URL}\n")
    text = urllib.request.urlopen(APNIC_URL, timeout=30).read().decode()
    intervals = []
    for line in text.splitlines():
        parts = line.split("|")
        if len(parts) < 5 or parts[2] != "ipv4" or parts[1] != "CN":
            continue
        start = int(ipaddress.IPv4Address(parts[3]))
        count = int(parts[4])
        intervals.append((start, start + count))  # [start, end)
    return intervals


def merge(intervals):
    out = []
    for s, e in sorted(intervals):
        if out and s <= out[-1][1]:
            out[-1] = (out[-1][0], max(out[-1][1], e))
        else:
            out.append((s, e))
    return out


def intervals_to_cidrs(intervals):
    out = []
    for s, e in intervals:
        out.extend(str(c) for c in ipaddress.summarize_address_range(
            ipaddress.IPv4Address(s), ipaddress.IPv4Address(e - 1)))
    return out


def cidrs_to_intervals(cidrs):
    return [(int(c.network_address), int(c.broadcast_address) + 1)
            for c in (ipaddress.ip_network(x) for x in cidrs)]


def subtract(base, cuts):
    """base/cuts: sorted disjoint [s,e) lists. Returns base minus cuts."""
    out = []
    for s, e in base:
        cur = s
        for cs, ce in cuts:
            if ce <= cur:
                continue
            if cs >= e:
                break
            if cs > cur:
                out.append((cur, cs))
            cur = max(cur, ce)
            if cur >= e:
                break
        if cur < e:
            out.append((cur, e))
    return merge(out)


def main():
    cn = merge(fetch_cn_intervals())
    cn_cidrs = intervals_to_cidrs(cn)
    sys.stderr.write(f"CN intervals: {len(cn)}, CIDRs after merge: {len(cn_cidrs)}\n")

    header = (f"# China mainland IPv4 ranges, aggregated from APNIC\n"
              f"# delegation data. Generated by scripts/update-chnroute.sh;\n"
              f"# do not edit by hand.\n")
    body = "\n".join(cn_cidrs) + "\n"
    for path in ("configs/chnroute_v4.txt",
                 "cmd/chimerac/chnroute_v4.txt",
                 "apps/windows/internal/bridge/chnroute_v4.txt"):
        with open(path, "w") as f:
            f.write(header + body)
    sys.stderr.write("wrote chnroute_v4.txt (3 copies)\n")

    # Android whitelist: complement of (CN ∪ private/reserved).
    full = [(0, 1 << 32)]
    cuts = merge(cidrs_to_intervals(cn_cidrs) + cidrs_to_intervals(PRIVATE))
    allow = subtract(full, cuts)
    allow_cidrs = intervals_to_cidrs(allow)
    sys.stderr.write(f"Android whitelist CIDRs: {len(allow_cidrs)}\n")

    with open("apps/android/app/src/main/res/values/split_routes_geo.xml", "w") as f:
        f.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
        f.write("<!-- Geo-split whitelist: public space OUTSIDE mainland China\n"
                "     (complement of CN ∪ private/reserved), generated by\n"
                "     scripts/update-chnroute.sh; do not edit by hand. -->\n")
        f.write("<resources>\n")
        f.write("    <string-array name=\"split_tunnel_geo_routes\">\n")
        for c in allow_cidrs:
            f.write(f"        <item>{c}</item>\n")
        f.write("    </string-array>\n")
        f.write("</resources>\n")
    sys.stderr.write("wrote split_routes_geo.xml\n")


if __name__ == "__main__":
    main()
